name: Test Build

on:
  pull_request:
    branches:
      - develop

jobs:
  check-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Build Frontend
        run: |
          npm install
          npm run build

      - name: Build Server
        run: |
          cd server
          npm ci
          npm run build